chore(copy): Copy changes over from llamastack/ org repository (#255)
Copying over content from llamastack/ as we run a slightly complex
manuever to transparently redirect _this_ repo to the other place.

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -1,59 +1,61 @@
 #!/usr/bin/env bash
 
-# set -e
+set -e
 
-# cd "$(dirname "$0")/.."
+cd "$(dirname "$0")/.."
 
-# RED='\033[0;31m'
-# GREEN='\033[0;32m'
-# YELLOW='\033[0;33m'
-# NC='\033[0m' # No Color
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[0;33m'
+NC='\033[0m' # No Color
 
-# function prism_is_running() {
-#   curl --silent "http://localhost:4010" >/dev/null 2>&1
-# }
+function prism_is_running() {
+  curl --silent "http://localhost:4010" >/dev/null 2>&1
+}
 
-# kill_server_on_port() {
-#   pids=$(lsof -t -i tcp:"$1" || echo "")
-#   if [ "$pids" != "" ]; then
-#     kill "$pids"
-#     echo "Stopped $pids."
-#   fi
-# }
+kill_server_on_port() {
+  pids=$(lsof -t -i tcp:"$1" || echo "")
+  if [ "$pids" != "" ]; then
+    kill "$pids"
+    echo "Stopped $pids."
+  fi
+}
 
-# function is_overriding_api_base_url() {
-#   [ -n "$TEST_API_BASE_URL" ]
-# }
+function is_overriding_api_base_url() {
+  [ -n "$TEST_API_BASE_URL" ]
+}
 
-# if ! is_overriding_api_base_url && ! prism_is_running ; then
-#   # When we exit this script, make sure to kill the background mock server process
-#   trap 'kill_server_on_port 4010' EXIT
+if ! is_overriding_api_base_url && ! prism_is_running ; then
+  # When we exit this script, make sure to kill the background mock server process
+  trap 'kill_server_on_port 4010' EXIT
 
-#   # Start the dev server
-#   ./scripts/mock --daemon
-# fi
+  # Start the dev server
+  ./scripts/mock --daemon
+fi
 
-# if is_overriding_api_base_url ; then
-#   echo -e "${GREEN}✔ Running tests against ${TEST_API_BASE_URL}${NC}"
-#   echo
-# elif ! prism_is_running ; then
-#   echo -e "${RED}ERROR:${NC} The test suite will not run without a mock Prism server"
-#   echo -e "running against your OpenAPI spec."
-#   echo
-#   echo -e "To run the server, pass in the path or url of your OpenAPI"
-#   echo -e "spec to the prism command:"
-#   echo
-#   echo -e "  \$ ${YELLOW}npm exec --package=@stoplight/prism-cli@~5.3.2 -- prism mock path/to/your.openapi.yml${NC}"
-#   echo
+if is_overriding_api_base_url ; then
+  echo -e "${GREEN}✔ Running tests against ${TEST_API_BASE_URL}${NC}"
+  echo
+elif ! prism_is_running ; then
+  echo -e "${RED}ERROR:${NC} The test suite will not run without a mock Prism server"
+  echo -e "running against your OpenAPI spec."
+  echo
+  echo -e "To run the server, pass in the path or url of your OpenAPI"
+  echo -e "spec to the prism command:"
+  echo
+  echo -e "  \$ ${YELLOW}npm exec --package=@stainless-api/prism-cli@5.15.0 -- prism mock path/to/your.openapi.yml${NC}"
+  echo
 
-#   exit 1
-# else
-#   echo -e "${GREEN}✔ Mock prism server is running with your OpenAPI spec${NC}"
-#   echo
-# fi
+  exit 1
+else
+  echo -e "${GREEN}✔ Mock prism server is running with your OpenAPI spec${NC}"
+  echo
+fi
 
-# echo "==> Running tests"
-# rye run pytest "$@"
+export DEFER_PYDANTIC_BUILD=false
 
-# echo "==> Running Pydantic v1 tests"
-# rye run nox -s test-pydantic-v1 -- "$@"
+echo "==> Running tests"
+rye run pytest "$@"
+
+echo "==> Running Pydantic v1 tests"
+rye run nox -s test-pydantic-v1 -- "$@"
